spring:
  application:
    name: consumer
  cloud:
    function:
      definition: riderLocation
    stream:
      function:
        definition: riderLocation
        binding:
          riderLocation-in-0:
            destination: my-topic-new
            content-type: application/json
        poller:
          fixed-delay: 5000
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092          # fix: 'bootstrap-server' â†’ 'bootstrap-servers'
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: '*'
#        spring.json.value.default.type: com.consumer.consumer.RiderLocation
server:
  port: 8081
