spring:
  application:
    name: producer
  cloud:
    function:
      definition: sendRiderLocation
    stream:
      function:
        definition: sendRiderLocation
      bindings:
        sendRiderLocation-out-0:
          destination: my-new-topic
          content-type: application/json
      poller:
        fixed-delay: 5000
      kafka:
        binder:
          brokers: localhost:9092



#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.value.default.type: com.demo.demo.controller.RiderLocation
#        spring.json.add.type.headers: false
#  cloud:
#    function:
#      definition: uppercase
#    function.web.path: /uppercase

